CU-cn24gw CU-cn24dh Remove extension and higherkind annotations for Endo and Eval
arrow-kt/arrow-core pull request #316
Opened 2021-01-26 12:17 UTC by danimontoya

- Remove extension annotation for Endo
- Remove extension and higherkind annotations for Eval

2021-01-26 12:17 UTC, franciscodr commented
Task linked: [CU-cn24dh Remove extension annotation Endo](https://app.clickup.com/t/cn24dh)

2021-01-26 12:17 UTC, franciscodr commented
Task linked: [CU-cn24gw Remove extension annotation Eval](https://app.clickup.com/t/cn24gw)

2021-01-28 14:21 UTC, nomisRev commented on arrow-core/src/main/kotlin/arrow/core/extensions/endo/monoid/EndoMonoid.kt
> +    "if (isEmpty()) empty() else reduce { a, b -> a.combine(b) }"
`combine` is not defined on `Endo`.

2021-01-28 14:22 UTC, nomisRev requested changes
Looks great! Only `combine` missing on `Endo` itself.

2021-01-29 13:01 UTC, nomisRev commented on arrow-core-data/src/main/kotlin/arrow/core/Endo.kt
> +
```suggestion
  fun combine(g: Endo<A>): Endo<A> =
    Endo(f.compose(g.f))
}
```

2021-02-02 10:22 UTC, nomisRev reviewed
A couple of incorrect deprecations, and nits.
Great work!! 👏 👏

2021-02-02 10:22 UTC, nomisRev commented on arrow-core/src/main/kotlin/arrow/core/extensions/endo/monoid/EndoMonoid.kt
> +@Deprecated("Monoid typeclasses is deprecated. Use concrete methods on Endo")
```suggestion
@Deprecated("Extension projections are deprecated. Use endo on Monoid.", ReplaceWith("Monoid.endo()", "arrow.typeclasses.Monoid", "arrow.core.endo")
```

2021-02-02 10:22 UTC, nomisRev commented on arrow-core-data/src/main/kotlin/arrow/core/Eval.kt
>      fun <A> just(a: A): Eval<A> =
Should be deprecated in favor of `now`

2021-02-02 10:22 UTC, nomisRev commented on arrow-core/src/main/kotlin/arrow/core/extensions/eval/applicative/EvalApplicative.kt
> +    "arrow.core.just"
```suggestion
    "Eval.now(this)",
    "arrow.core.Eval"
```

2021-02-02 10:22 UTC, nomisRev commented on arrow-core/src/main/kotlin/arrow/core/extensions/eval/applicative/EvalApplicative.kt
> +    "arrow.core.just"
```suggestion
    "Eval.Unit",
    "arrow.core.Eval"
```

2021-02-02 10:22 UTC, nomisRev commented on arrow-core/src/main/kotlin/arrow/core/extensions/eval/apply/EvalApply.kt
> +    "arrow.core.Eval"
```suggestion
    "Eval.mapN(arg0, arg1) { a, b -> arg2(Tuple2(a, b)) }",
    "arrow.core.Eval", "arrow.core.Tuple2"
```

Idem for other `map` & `mapN` methods.

2021-02-02 10:22 UTC, nomisRev commented on arrow-core/src/main/kotlin/arrow/core/extensions/eval/apply/EvalApply.kt
> +    "arrow.core.Eval"
```suggestion
    "Eval.mapN(this, fb) { a, b -> Tuple2(a, b) }",
    "arrow.core.Eval", "arrow.core.Tuple2"
```

2021-02-02 10:22 UTC, nomisRev commented on arrow-core/src/main/kotlin/arrow/core/extensions/eval/apply/EvalApply.kt
> +    "arrow.core.Eval"
```suggestion
    "Eval.mapN(this, fb) { ab, c -> Tuple3(ab.a, ab.b, c) }",
    "arrow.core.Eval", "arrow.core.Tuple3"
```

Idem for other `product` methods

2021-02-02 10:22 UTC, nomisRev commented on arrow-core/src/main/kotlin/arrow/core/extensions/eval/apply/EvalApply.kt
> +    "arrow.core.Eval"
```suggestion
    "arrow.core.Eval", "arrow.core.Tuple2"
```

Same for other `tupled`/`tupledN` methods

2021-02-02 10:22 UTC, nomisRev commented on arrow-core/src/main/kotlin/arrow/core/extensions/eval/comonad/EvalComonad.kt
> +    "arrow.core.extract"
```suggestion
    "value()"
```

2021-02-02 10:22 UTC, nomisRev commented on arrow-core-data/src/main/kotlin/arrow/core/Eval.kt
>    fun extract(): A = value()
Deprecate in favor of `value()`. No need to duplicate the `Comonad` API here.

2021-02-02 11:14 UTC, nomisRev approved these changes
Looks great @danimontoya! 👏 👏 👏 Thanks 🙏

2021-02-02 11:21 UTC, danimontoya commented
@nomisRev thanks to you for all the reviews 🙌  😄

2021-02-03 08:58 UTC, i-walker commented on arrow-core-data/src/main/kotlin/arrow/core/Eval.kt
> +      mapN(a, b, c, Unit, Unit, Unit, Unit, Unit, Unit, Unit) { aa, bb, cc, _, _, _, _, _, _, _ -> map(aa, bb, cc) }
nit:
with the kotlin naming conventions wouldn't we define `Unit` starting with a lowercase letter same there too
https://github.com/arrow-kt/arrow-core/blob/01781b8380401f0f1d2bc60edb234bcb23aec41b/arrow-core-data/src/main/kotlin/arrow/core/Eval.kt#L175-L183

2021-02-03 09:02 UTC, i-walker approved these changes
Looks great @danimontoya 🙌 
Just left a nit there, so those members are consistent across libraries in terms of naming conventions.

2021-02-03 11:14 UTC, merged